
INSERT INTO CLP.STRUCTURED.DIM_DATE(

WITH CTE_MY_DATE AS (
SELECT DATEADD(DAY, SEQ4(), '2016-01-01 00:00:00') AS MY_DATE
FROM TABLE(GENERATOR(ROWCOUNT=>5000))
)
SELECT
TO_DATE(MY_DATE) as CALENDAR_DATE
,YEAR(MY_DATE) as YEAR
,MONTH(MY_DATE) as MONTH
,MONTHNAME(MY_DATE) as MONTH_NAME
,QUARTER(MY_DATE) as QUARTER
,DAYOFWEEK(MY_DATE) as DAY_OF_WEEK
,DAYNAME(MY_DATE) as DAY_NAME
,WEEKOFYEAR(MY_DATE) as WEEK_OF_YEAR
,DAYOFYEAR(MY_DATE) as DAY_OF_YEAR

FROM CTE_MY_DATE
);

select * from CLP.STRUCTURED.DIM_DATE